### PR TITLE
Feature/dt 46

### PR DESCRIPTION
**Pull request by DavidSmagly**
UI component DT-46, changed img src -> ngSrc

### CODE REVIEW

**Comment by mrrhetorical** [comment]
The UI stuff looks great, can you maybe create a single edit button that will turn each field on the patient information into an editable field and then have a save button show up once you are in "edit mode" that will then submit the new information. If you'd like some help with this I can provide some guidance.

**Comment by DavidSmagly** [comment]
adding requested changes

**Comment by DavidSmagly** [comment]
added changes

**Review by mrrhetorical — APPROVED** [review]
LGTC

**Pull request merged**
